// seed-data.js
const { Client } = require('pg');
require('dotenv').config();

const sampleRoomies = [
  {
    id: "1",
    name: "Josué Chaves",
    age: 28,
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    verified: true,
    rating: 4.5,
    reviews: 12,
    location: "San José, Costa Rica",
    hasApartment: true,
    budget: { min: 300, max: 600 },
    bio: "Apasionado por la tecnología y desarrollo de software. Me gusta mantener mi espacio limpio y ordenado.",
    interests: ["Cocina", "Deportes", "Lectura", "Viajes", "Música"],
    occupation: "Ingeniero en Computación",
    socialLevel: 4,
    cleanlinessLevel: 5,
    acceptsSmokers: true,
    acceptsPets: false,
    acceptsGuests: true,
    languages: ["Español", "Inglés"],
    photos: ["https://picsum.photos/400/300?random=1", "https://picsum.photos/400/300?random=2"]
  },
  {
    id: "2",
    name: "María López",
    age: 25,
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    verified: false,
    rating: 4.0,
    reviews: 8,
    location: "Alajuela, Costa Rica",
    hasApartment: false,
    budget: { min: 250, max: 500 },
    bio: "Amante de los animales y la naturaleza. Busco un lugar tranquilo y ordenado.",
    interests: ["Yoga", "Viajes", "Fotografía", "Cine"],
    occupation: "Diseñadora Gráfica",
    socialLevel: 3,
    cleanlinessLevel: 4,
    acceptsSmokers: false,
    acceptsPets: true,
    acceptsGuests: false,
    languages: ["Español", "Inglés"],
    photos: ["https://picsum.photos/400/300?random=3", "https://picsum.photos/400/300?random=4"]
  },
  {
    id: "3",
    name: "Carlos Fernández",
    age: 30,
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    verified: true,
    rating: 4.8,
    reviews: 20,
    location: "Heredia, Costa Rica",
    hasApartment: true,
    budget: { min: 400, max: 700 },
    bio: "Ingeniero de software. Me gusta la música y hacer deporte en mi tiempo libre.",
    interests: ["Música", "Deportes", "Videojuegos"],
    occupation: "Ingeniero de Software",
    socialLevel: 4,
    cleanlinessLevel: 4,
    acceptsSmokers: false,
    acceptsPets: true,
    acceptsGuests: true,
    languages: ["Español", "Inglés", "Portugués"],
    photos: ["https://picsum.photos/400/300?random=5", "https://picsum.photos/400/300?random=6"]
  },
  {
    id: "4",
    name: "Ana Rodríguez",
    age: 27,
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    verified: false,
    rating: 3.9,
    reviews: 5,
    location: "Cartago, Costa Rica",
    hasApartment: false,
    budget: { min: 200, max: 450 },
    bio: "Me encanta leer y cocinar. Busco un ambiente tranquilo y amigable.",
    interests: ["Lectura", "Cocina", "Arte", "Viajes"],
    occupation: "Profesora",
    socialLevel: 3,
    cleanlinessLevel: 4,
    acceptsSmokers: false,
    acceptsPets: true,
    acceptsGuests: true,
    languages: ["Español"],
    photos: ["https://picsum.photos/400/300?random=7"]
  },
  {
    id: "5",
    name: "Luis Gómez",
    age: 32,
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    verified: true,
    rating: 4.7,
    reviews: 15,
    location: "Puntarenas, Costa Rica",
    hasApartment: true,
    budget: { min: 350, max: 650 },
    bio: "Apasionado por los deportes y la tecnología. Me gusta mantener todo organizado.",
    interests: ["Deportes", "Tecnología", "Cine", "Viajes"],
    occupation: "Arquitecto",
    socialLevel: 4,
    cleanlinessLevel: 5,
    acceptsSmokers: false,
    acceptsPets: true,
    acceptsGuests: true,
    languages: ["Español", "Inglés"],
    photos: ["https://picsum.photos/400/300?random=8", "https://picsum.photos/400/300?random=9"]
  },
  {
    id: "6",
    name: "Sofía Méndez",
    age: 24,
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
    verified: true,
    rating: 4.3,
    reviews: 10,
    location: "San José, Costa Rica",
    hasApartment: false,
    budget: { min: 280, max: 550 },
    bio: "Estudiante de diseño gráfico, creativa y organizada.",
    interests: ["Arte", "Música", "Cine", "Fotografía"],
    occupation: "Estudiante",
    socialLevel: 3,
    cleanlinessLevel: 4,
    acceptsSmokers: false,
    acceptsPets: false,
    acceptsGuests: true,
    languages: ["Español", "Inglés"],
    photos: ["https://picsum.photos/400/300?random=10"]
  },
  {
    id: "7",
    name: "Andrés Castillo",
    age: 29,
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    verified: false,
    rating: 4.1,
    reviews: 7,
    location: "Heredia, Costa Rica",
    hasApartment: true,
    budget: { min: 300, max: 600 },
    bio: "Trabajo en marketing digital. Me gusta el ejercicio y cocinar.",
    interests: ["Gimnasio", "Cocina", "Viajes", "Series"],
    occupation: "Marketing Digital",
    socialLevel: 4,
    cleanlinessLevel: 3,
    acceptsSmokers: true,
    acceptsPets: true,
    acceptsGuests: true,
    languages: ["Español"],
    photos: ["https://picsum.photos/400/300?random=11", "https://picsum.photos/400/300?random=12"]
  },
  {
    id: "8",
    name: "Gabriela Rojas",
    age: 26,
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
    verified: true,
    rating: 4.6,
    reviews: 14,
    location: "Cartago, Costa Rica",
    hasApartment: false,
    budget: { min: 250, max: 500 },
    bio: "Soy maestra y disfruto mucho la lectura y el cine.",
    interests: ["Lectura", "Cine", "Yoga", "Naturaleza"],
    occupation: "Maestra",
    socialLevel: 3,
    cleanlinessLevel: 5,
    acceptsSmokers: false,
    acceptsPets: true,
    acceptsGuests: false,
    languages: ["Español"],
    photos: ["https://picsum.photos/400/300?random=13"]
  },
  {
    id: "9",
    name: "Daniel Vargas",
    age: 31,
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
    verified: true,
    rating: 4.7,
    reviews: 18,
    location: "Alajuela, Costa Rica",
    hasApartment: true,
    budget: { min: 400, max: 750 },
    bio: "Ingeniero civil. Me gustan los deportes y la música.",
    interests: ["Deportes", "Música", "Viajes", "Cocina"],
    occupation: "Ingeniero Civil",
    socialLevel: 4,
    cleanlinessLevel: 4,
    acceptsSmokers: false,
    acceptsPets: true,
    acceptsGuests: true,
    languages: ["Español", "Inglés"],
    photos: ["https://picsum.photos/400/300?random=14", "https://picsum.photos/400/300?random=15"]
  },
  {
    id: "10",
    name: "Valeria Jiménez",
    age: 23,
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
    verified: false,
    rating: 3.8,
    reviews: 6,
    location: "Puntarenas, Costa Rica",
    hasApartment: false,
    budget: { min: 200, max: 400 },
    bio: "Me encantan los animales y la vida tranquila cerca de la playa.",
    interests: ["Surf", "Naturaleza", "Fotografía", "Cocina"],
    occupation: "Fotógrafa",
    socialLevel: 3,
    cleanlinessLevel: 3,
    acceptsSmokers: false,
    acceptsPets: true,
    acceptsGuests: true,
    languages: ["Español", "Inglés"],
    photos: ["https://picsum.photos/400/300?random=16"]
  },
  {
    id: "11",
    name: "Ricardo Morales",
    age: 27,
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    verified: true,
    rating: 4.4,
    reviews: 12,
    location: "San José, Costa Rica",
    hasApartment: true,
    budget: { min: 350, max: 600 },
    bio: "Programador freelance, tranquilo y responsable.",
    interests: ["Tecnología", "Videojuegos", "Cine", "Música"],
    occupation: "Freelancer",
    socialLevel: 3,
    cleanlinessLevel: 5,
    acceptsSmokers: false,
    acceptsPets: false,
    acceptsGuests: true,
    languages: ["Español", "Inglés"],
    photos: ["https://picsum.photos/400/300?random=17", "https://picsum.photos/400/300?random=18"]
  },
  {
    id: "12",
    name: "Laura Herrera",
    age: 28,
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    verified: false,
    rating: 4.0,
    reviews: 9,
    location: "Heredia, Costa Rica",
    hasApartment: false,
    budget: { min: 300, max: 550 },
    bio: "Apasionada por la cocina y la lectura.",
    interests: ["Cocina", "Lectura", "Viajes", "Arte"],
    occupation: "Chef",
    socialLevel: 3,
    cleanlinessLevel: 4,
    acceptsSmokers: false,
    acceptsPets: true,
    acceptsGuests: true,
    languages: ["Español"],
    photos: ["https://picsum.photos/400/300?random=19"]
  },
  {
    id: "13",
    name: "José Ramírez",
    age: 33,
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
    verified: true,
    rating: 4.9,
    reviews: 21,
    location: "Cartago, Costa Rica",
    hasApartment: true,
    budget: { min: 450, max: 800 },
    bio: "Médico general, responsable y ordenado.",
    interests: ["Deportes", "Viajes", "Lectura", "Cine"],
    occupation: "Médico",
    socialLevel: 4,
    cleanlinessLevel: 5,
    acceptsSmokers: false,
    acceptsPets: false,
    acceptsGuests: false,
    languages: ["Español", "Inglés"],
    photos: ["https://picsum.photos/400/300?random=20", "https://picsum.photos/400/300?random=21"]
  },
  {
    id: "14",
    name: "Camila Soto",
    age: 26,
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
    verified: true,
    rating: 4.5,
    reviews: 11,
    location: "San José, Costa Rica",
    hasApartment: false,
    budget: { min: 270, max: 500 },
    bio: "Trabajo en moda, me gusta la fotografía y el diseño.",
    interests: ["Fotografía", "Arte", "Música", "Yoga"],
    occupation: "Diseñadora de Moda",
    socialLevel: 4,
    cleanlinessLevel: 4,
    acceptsSmokers: false,
    acceptsPets: false,
    acceptsGuests: true,
    languages: ["Español", "Inglés"],
    photos: ["https://picsum.photos/400/300?random=22"]
  },
  {
    id: "15",
    name: "Felipe Navarro",
    age: 29,
    avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    verified: false,
    rating: 3.7,
    reviews: 5,
    location: "Alajuela, Costa Rica",
    hasApartment: false,
    budget: { min: 250, max: 480 },
    bio: "Estudiante de arquitectura, creativo y sociable.",
    interests: ["Arquitectura", "Deportes", "Cine", "Viajes"],
    occupation: "Estudiante",
    socialLevel: 4,
    cleanlinessLevel: 3,
    acceptsSmokers: true,
    acceptsPets: true,
    acceptsGuests: true,
    languages: ["Español"],
    photos: ["https://picsum.photos/400/300?random=23"]
  },
  {
    id: "16",
    name: "Natalia Vega",
    age: 27,
    avatar: "https://randomuser.me/api/portraits/women/16.jpg",
    verified: true,
    rating: 4.6,
    reviews: 13,
    location: "Heredia, Costa Rica",
    hasApartment: true,
    budget: { min: 320, max: 600 },
    bio: "Amante de los animales y el senderismo.",
    interests: ["Naturaleza", "Deportes", "Viajes", "Lectura"],
    occupation: "Veterinaria",
    socialLevel: 4,
    cleanlinessLevel: 5,
    acceptsSmokers: false,
    acceptsPets: true,
    acceptsGuests: true,
    languages: ["Español"],
    photos: ["https://picsum.photos/400/300?random=24", "https://picsum.photos/400/300?random=25"]
  },
  {
    id: "17",
    name: "Javier Pineda",
    age: 30,
    avatar: "https://randomuser.me/api/portraits/men/17.jpg",
    verified: true,
    rating: 4.2,
    reviews: 9,
    location: "Cartago, Costa Rica",
    hasApartment: true,
    budget: { min: 370, max: 650 },
    bio: "Analista financiero, responsable y tranquilo.",
    interests: ["Cine", "Música", "Deportes", "Viajes"],
    occupation: "Analista Financiero",
    socialLevel: 3,
    cleanlinessLevel: 5,
    acceptsSmokers: false,
    acceptsPets: false,
    acceptsGuests: false,
    languages: ["Español", "Inglés"],
    photos: ["https://picsum.photos/400/300?random=26"]
  },
  {
    id: "18",
    name: "Isabella Mora",
    age: 24,
    avatar: "https://randomuser.me/api/portraits/women/18.jpg",
    verified: false,
    rating: 3.9,
    reviews: 6,
    location: "Puntarenas, Costa Rica",
    hasApartment: false,
    budget: { min: 200, max: 420 },
    bio: "Estudiante de turismo, me encanta conocer nuevas culturas.",
    interests: ["Viajes", "Naturaleza", "Música", "Cine"],
    occupation: "Estudiante",
    socialLevel: 4,
    cleanlinessLevel: 3,
    acceptsSmokers: false,
    acceptsPets: true,
    acceptsGuests: true,
    languages: ["Español", "Inglés"],
    photos: ["https://picsum.photos/400/300?random=27"]
  },
  {
    id: "19",
    name: "Diego León",
    age: 32,
    avatar: "https://randomuser.me/api/portraits/men/19.jpg",
    verified: true,
    rating: 4.8,
    reviews: 16,
    location: "San José, Costa Rica",
    hasApartment: true,
    budget: { min: 400, max: 700 },
    bio: "Consultor en tecnología, ordenado y social.",
    interests: ["Tecnología", "Deportes", "Cocina", "Viajes"],
    occupation: "Consultor TI",
    socialLevel: 4,
    cleanlinessLevel: 4,
    acceptsSmokers: false,
    acceptsPets: true,
    acceptsGuests: true,
    languages: ["Español", "Inglés"],
    photos: ["https://picsum.photos/400/300?random=28", "https://picsum.photos/400/300?random=29"]
  },
  {
    id: "20",
    name: "Fernanda Araya",
    age: 25,
    avatar: "https://randomuser.me/api/portraits/women/20.jpg",
    verified: true,
    rating: 4.4,
    reviews: 12,
    location: "Alajuela, Costa Rica",
    hasApartment: false,
    budget: { min: 250, max: 500 },
    bio: "Diseñadora de interiores, creativa y amigable.",
    interests: ["Arte", "Diseño", "Música", "Yoga"],
    occupation: "Diseñadora de Interiores",
    socialLevel: 4,
    cleanlinessLevel: 4,
    acceptsSmokers: false,
    acceptsPets: false,
    acceptsGuests: true,
    languages: ["Español", "Inglés"],
    photos: ["https://picsum.photos/400/300?random=30"]
  },
  {
    id: "21",
    name: "Mauricio Solís",
    age: 28,
    avatar: "https://randomuser.me/api/portraits/men/21.jpg",
    verified: false,
    rating: 4.0,
    reviews: 8,
    location: "Heredia, Costa Rica",
    hasApartment: true,
    budget: { min: 300, max: 580 },
    bio: "Estudiante de ingeniería, tranquilo y sociable.",
    interests: ["Videojuegos", "Cine", "Deportes", "Música"],
    occupation: "Estudiante",
    socialLevel: 4,
    cleanlinessLevel: 3,
    acceptsSmokers: true,
    acceptsPets: true,
    acceptsGuests: true,
    languages: ["Español"],
    photos: ["https://picsum.photos/400/300?random=31", "https://picsum.photos/400/300?random=32"]
  }
];

async function seedDatabase() {
  const client = new Client({
    connectionString: process.env.DATABASE_URL || 'postgresql://citus:Roomiefy2301@c-roomies-postgres-db.t66x6mz43vydno.postgres.cosmos.azure.com:5432/roomies_db?sslmode=require',
    ssl: {
      rejectUnauthorized: false
    }
  });

  try {
    await client.connect();
    console.log('🔗 Conectado a la base de datos Azure Cosmos DB');

    // Limpiar datos existentes
    await client.query('DELETE FROM roomies');
    console.log('🧹 Datos existentes eliminados');

    // Insertar datos de muestra
    for (const roomie of sampleRoomies) {
      const query = `
        INSERT INTO roomies (
          id, name, age, avatar, verified, rating, reviews, location,
          "hasApartment", budget, bio, interests, occupation, "socialLevel",
          "cleanlinessLevel", "acceptsSmokers", "acceptsPets", "acceptsGuests",
          languages, photos, "createdAt"
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
      `;

      const values = [
        roomie.id, roomie.name, roomie.age, roomie.avatar, roomie.verified,
        roomie.rating, roomie.reviews, roomie.location, roomie.hasApartment,
        JSON.stringify(roomie.budget), roomie.bio, JSON.stringify(roomie.interests),
        roomie.occupation, roomie.socialLevel, roomie.cleanlinessLevel,
        roomie.acceptsSmokers, roomie.acceptsPets, roomie.acceptsGuests,
        JSON.stringify(roomie.languages), JSON.stringify(roomie.photos),
        new Date().toISOString()
      ];

      await client.query(query, values);
      console.log(`✅ Roomie insertado: ${roomie.name}`);
    }

    console.log('🎉 ¡Datos de muestra insertados exitosamente!');

    // Verificar que se insertaron correctamente
    const result = await client.query('SELECT COUNT(*) as count FROM roomies');
    console.log(`📊 Total de roomies en la base de datos: ${result.rows[0].count}`);

  } catch (error) {
    console.error('❌ Error al poblar la base de datos:', error.message);
    console.error('Error completo:', error);
  } finally {
    await client.end();
    console.log('🔌 Conexión cerrada');
  }
}

seedDatabase();